### ISSUE TITLE
[Question] How can we improve the Appverse?

### ISSUE THREAD

**Issue by rafaell-lycan** [Appverse/appverse-web-html5-core#26]
Hey guys, I just started using Appverse here in GFT and I got some stuff that probably could be improved.

I know that maybe you already had a kind of roadmap of improvements, but I´m using for few weeks and some stuff that I saw we can improve step by step.

**Possible improvements**
- Even though we're using Bootstrap, I´m not sure if the way we're using it's correct. Maybe we could create a based styleguide with few components that we can share and import only the necessary things of Bootstrap instead all components.
- Another thing that maybe could be a great is to define a based folder structure to styles and components following directives like SMACSS, BEM, OOCSS or even few pieces of each one. This way we can really improve the project along the time and maybe in the future even use more components made by ourselves then bootstrap stuff.
- Replace Grunt by Gulp. I know that Grunt is an amazing task runner, but by migrating to Gulp we can use convention instead of configuration and also improve our tasks and build process. Webpack is an option as well, but I personally prefer Gulp instead.
- Remove Ionic from the web version. Why are we loading Ionic dependencies if the project is to the web? I totally support PWA, but I don't think that load unnecessary stuff that probably isn't used in all projects is a good approach. Let's try to keep things simple.
- Define useful modules/services that could help us during the development process or even use some opensource solution.

**Nice to Have**
- Add ES6 support with Babel and Browserify (With polyfills, and even ES7 support like async/await that it's in stage-3 now).
- Change JSHint to ESLint and start using Airbnb code standard.
- Do we really need Lodash?

**PS:** Have you ever heard about [FountainJS](http://fountainjs.io/)?

That's it, let the discussion begin. 🏇 💨

**Comment by aecz** [comment]
This issue has not been answered and is very old, sorry for that.
This project has stopped being developed as you can see, so we now only accept pull requests.
