### ISSUE TITLE
Conflict with angular-translate and appverse-translate

### ISSUE THREAD

**Issue by ArnauAregall** [Appverse/appverse-web-html5-core#27]
Hello,

We've been using Appverse as bootstrap solution in a client's HTML5 and SPA architecture, and we received internal issues regarding the performance of the translation module (appverse-translation).

The developers tried to upgrade angular-translate by themselves but reported conflicts with the appverse-translate module:

```javascript
function decorateTranslateDirective($delegate, translateFilter) {

        // Get the original directive and its linking function
        var directive = $delegate[0];
        var originalLinkFunction = directive.link;
```

In the latest versions of `angular-translate` handles the directive.link internally in the `compile` function of itself, so `originalLinkFunction` becomes `undefined`.

How this could be fixed so we can upgrade properly the `angular-translate` module of our applications without conflict with your library?

Thank you,
Arnau.

**Comment by aecz** [comment]
Hi, thanks for using this library.
Unfortunately, we do not test this project to work with latest versions of `angular-translate` nor any third party library.
However, we do accept pull requests so you could create one that would include the newest version of `angular-translate` and the fix of the `appverse-translate` module.
Let me know if you need more information.

**Comment by ArnauAregall** [comment]
Hi @aecz , thank you for the fast response! I'll explain the situation to my client.

Lets suppose for now that the pull request will be done and merged; a new release of `appverse-web-html5-core` would be published by Appverse on npm right?

**Comment by aecz** [comment]
@ArnauAregall you are right. We would publish a new version.

**Comment by ArnauAregall** [comment]
@aecz Pull request opened to upgrade angular-translate version:

#28

**Comment by ArnauAregall** [comment]
Closing since #28 has been merged. Thank you @aecz .
